### ISSUE TITLE
Fresh install need to restart after pg_hba.conf

### ISSUE THREAD

**Issue by Poil** [saltstack-formulas/postgres-formula#236]
Hi,

I've deployed a new postgresql server, it seems that the postgresql-pg_hba resource is not notifying the postgresql service (PG 10 on CentOS 7)

Best regards

**Comment by myii** [comment]
This was addressed by @RobRuana (with a proposed resolution): https://github.com/saltstack-formulas/postgres-formula/pull/216#discussion_r207033897.

**Comment by noelmcloughlin** [comment]
impacts Ubuntu too, see #216 (comment)

> I've found that simply reloading the postgres service is not enough to pick up ACL changes in pg_hba.conf. A full restart is required.
> This is on ubuntu 18.04 with postgres 10.

**Comment by danny-smit** [comment]
I just ran into this with Debian as well. It seems that triggering a reload manually does pick up the changes, but during the run of this formula it does not. 

Could it be that it is actually a race condition? As the formula executes the following steps:
1. update postgresql.conf
2. restart postgresql service
3. update pg_hba.conf
4. reload the postgresql service

Perhaps the reload (bullet 4) is ignored because the restart (of bullet 2) is still in progress?
