### ISSUE TITLE
tablespaces missing from example

### ISSUE THREAD

**Issue by jmdcal** [saltstack-formulas/postgres-formula#50]
it looks like tablespaces are missing from the example pillar but required by the template

**Comment by iggy** [comment]
They are in default.yaml (as of #49 ). I haven't added them to the pillar.example yet because I think I'm going to change the layout of the dict. When I first did the tablespace support all I supported was name/directory. When I did this round of ts support, I actually enabled the options/owner/etc support (but my original pillar structure didn't support that).

**Comment by vutny** [comment]
The `pillar.example` file already has `tablespaces` item. Looks like this is no longer an issue.
